apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sf-keytool
  namespace: platforce
  labels:
    team: platforce
spec:
  image: "{{ image }}"
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /internal/isAlive
  readiness:
    path: /internal/isReady
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    logging:
      destinations:
        - id: loki
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 10m
      memory: 512Mi
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-f1-micro
        databases:
          - name: sf-keytool-dev
  ingresses:
    - "https://sf-keytool.intern.dev.nav.no"
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - azp_name
          - NAVident
#    sidecar:
#      enabled: false
  accessPolicy:
    outbound:
      external:
        - host: test.salesforce.com
        - host: hooks.slack.com
#  accessPolicy:
#    inbound:
#      rules:
#        - application: salesforce
#          namespace: teamcrm
#          cluster: dev-external
  envFrom:
    - secret: sf-pubsub-preprod
    - secret: sf-keytool
  env:
    - name: CONTEXT
      value: "DEV"
